### ISSUE TITLE
Temperature compensated humidity for SHT21

### ISSUE THREAD

**Issue by Diederikvanderpant** [enjoyneering/HTU21D#2]
Hi,

What is your source for the temperature compensation of the humidity at line 418 in  HTU21D.CPP . You claim it is valid for the SHT21 but I cannot any reference in the Sensirion datasheets for the SHT21. 

Sincerely,
Diederik vd Pant

**Comment by enjoyneering** [comment]
Good question.

The HTU21D datasheet from 2014, see  row "Temperature coefficient" in the table on page 3.

**Comment by Diederikvanderpant** [comment]
Hi,

Thanks for the answer! Out of curiosity.  How did you find out that HTUD21D
from MEAS and SHT21 from Sensirion are identical? Googling, it seems a lot
of people know about this. But their datasheets do not mention each
other....

Sincerely,

Deiderik





2017-04-12 14:03 GMT+02:00 enjoyneering <notifications@github.com>:

**Comment by enjoyneering** [comment]
Hi, Deiderik

Take a look at  Grath 1 on p. 4 of HTU21D datasheet and Figure 2 on p.2 of SHT21 . They are identical, plus returning the same chip ID, see readDeviceID() function.

The Si7021 is completely different beast. It's RH accuracy a little bit better, Figure 2 on p.8. And it looks like it does temp. compensation automatically, see readTemperature(HTU21D_TEMP_READ_AFTER_RH_MEASURMENT)). You have to call it after RH measurement.

All three sensors are very accurate and reliable, however if you just starting the project I'am suggesting BM**E**280. See the [article](http://www.kandrsmith.org/RJS/Misc/Hygrometers/calib_many.html).

**Comment by Diederikvanderpant** [comment]
Hi,
Thanks for the quick reply.
Will use your code in a testsetup with sht21's i am running. Btw in another
setup i am also very satisfied with the performance of sht31 and bme280 who
have Tcompensation integrated.
Sincerely,
Diederik




Op 12 apr. 2017 17:56 schreef "enjoyneering" <notifications@github.com>:
