### ISSUE TITLE
Fails with SHT21

### ISSUE THREAD

**Issue by fink42** [enjoyneering/HTU21D#7]
Hello

I am using the Wemos D1 mini Pro and a SHT21 sensor ([identical to this one:](https://www.aliexpress.com/item/cable-length-OEM-SHT10-SHT11-SHT15-SHT20-SHT21-SHT25-IIC-interface-Soil-temperature-and-humidity-sensor/32828229124.html?spm=2114.search0104.3.62.34d73b5aQXObb7&ws_ab_test=searchweb0_0,searchweb201602_8_10065_10068_319_317_10696_10084_453_10083_454_10618_10304_10307_10820_10821_537_10302_536_10902_10059_10884_10887_321_322_10103,searchweb201603_56,ppcSwitch_0&algo_expid=ee18dc61-cdd4-4df8-b51f-75eed07f7cf4-9&algo_pvid=ee18dc61-cdd4-4df8-b51f-75eed07f7cf4&transAbTest=ae803_4)).

I have connected the SDA from the sensor to D2 on the board and SCL from the sensor to D1 on the board. But all I'm getting is: "HTU21D, SHT21 sensor is faild or not connected", when I run the HTU21D_Demo.

When I run I2C scanner ([link](https://github.com/wemos/D1_mini_Examples/blob/master/examples/02.Special/Wire/I2C_Scanner/I2C_Scanner.ino)) it finds an I2C device at address 0x40 and nothing when I remove the sensor. So I guess the sensor is wired up correctly and there might be something else I am doing wrong/missing.

Hope you are able and willing to help me

**Comment by enjoyneering** [comment]
Hi,

try to replace
`while (myHTU21D.begin() != true)`
in HTU21D_Demo.ino with
`while (myHTU21D.begin(D2, D1) != true)`
