### ISSUE TITLE
Use of Delays

### ISSUE THREAD

**Issue by Raphael909** [enjoyneering/HTU21D#9]
Hello, Not an issue but a quick question. I was wondering what would be the reason for using blocking code i.e `use of delay function` while calculating Temperature and Humidity. 

I was thinking to go Non blocking using `millis`. Also not sure how you got to those number for delays for different resolution.
What are your thoughts ?

Thank you for your effort and putting this wonderful library in  public domain.

**Comment by enjoyneering** [comment]
Hi,

Delay is simpler and code is cleaner. You definitely can use millis().
